apiVersion: v1
kind: Service

metadata:
  name: ostad-node-service
  namespace: production

spec:
  type: NodePort

  selector:
    app: ostad-node-app

  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080